WTproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('welcome.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

welcome/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'welcome'

urlpatterns = [
    #/game
    url(r'^$',views.index, name='index'),
    url(r'^cart/$',views.cart, name='cart'),
    url(r'^login/$', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/$',views.logout_view, name="logout"),
    url(r'^register/$',views.UserFormView.as_view(), name='register'),

    url(r'^shop_man/$',views.shop_man, name='shop_man'),
    url(r'^shop_women/$',views.shop_women, name='shop_women'),
    url(r'^shop_kids/$',views.shop_kids, name='shop_kids'),

    url(r'^(?P<gender>\w+)/(?P<id>[0-9]+)/$',views.products,name='products'),

    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),

    url(r'(?P<pk>[0-9]+)/delete/$',views.ProductDelete.as_view(),name='product-delete'),


    url(r'^checkout/step1/$',views.AddressFormView.as_view(), name='step1'),
    url(r'^checkout/step2/$',views.checkoutStep2, name='step2'),
    url(r'^checkout/step2/(?P<id>[0-9]+)/$',views.checkoutStep3, name='step3'),
    url(r'^checkout/step3/$',views.checkoutStep4, name='step4'),

    ]

welcome/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy

# Create your models here.
class Address(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	address_line = models.CharField(max_length=500)
	city = models.CharField(max_length=255)
	state = models.CharField(max_length=255)
	pincode = models.IntegerField()
	phone_number = models.IntegerField()
	active = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

class Product(models.Model):
	category = models.ForeignKey(
	    'Category',
	    on_delete=models.CASCADE,
	    null=True,
	    blank=True,
	    related_name='category')
	title = models.CharField(max_length=255)
	description = models.TextField(blank=True)

	XS, S, M, L, XL, XXL  = ('XS', 'S', 'M', 'L', 'XL', 'XXL')
	SIZE_CHOICES = (
	    (XS, _("XS")),
	    (S, _("S")),
	    (M, _("M")),
	    (L, _("L")),
	    (XL, _("XL")),
	    (XXL, _("XXL")),
	)
	pimage = models.FileField(null=True)


	price = models.IntegerField()
	def __str__(self):
		return self.title + '-'+ self.category.title

	def get_absolute_url(self):
		return reverse('welcome:detail',kwargs={'pk':self.pk})

class Image(models.Model):
	product = models.ForeignKey(
	    'Product',
	    on_delete=models.CASCADE,
	    related_name='images')
	original = models.FileField()
	caption = models.CharField(max_length=200, blank=True)

	#: Use display_order to determine which is the "primary" image
	display_order = models.PositiveIntegerField(default=0)
	def __str__(self):
		return self.product.title 



class CartP(models.Model):
	user = models.ForeignKey(
        User, related_name='cart', null=True, blank=True,
        on_delete=models.SET_NULL)

	product = models.ForeignKey(
	    'Product',
	    on_delete=models.CASCADE)
	size = models.CharField(max_length=10)
	delivery_date = models.DateField()

	def __str__(self):
		return self.user.username + '-' + self.product.title

class Order(models.Model):

    # Orders can be placed without the user authenticating so we don't always
    # have a customer ID.
	user = models.ForeignKey(
        User, related_name='orders', null=True, blank=True,
        on_delete=models.SET_NULL)

	shipping_address = models.ForeignKey(
        'Address', null=True, blank=True,
        on_delete=models.SET_NULL)


    # Index added to this field for reporting
	date_placed = models.DateTimeField(auto_now=True,blank=True)
	def __str__(self):
		return self.user.username

class Category(models.Model):
	title = models.CharField(max_length=255)
	image = models.FileField()
	MEN, WOMEN, KIDS = ('Men', 'Women', 'Kids')
	GENDER_CHOICES = (
        (MEN, _("Men")),
        (WOMEN, _("Women")),
        (KIDS, _("Kids")),
    )

	gender = models.CharField(
    	pgettext_lazy(u"Product is available for", u"Available_for"),
	    max_length=64, choices=GENDER_CHOICES)

	"""def get_absolute_url(self):
		return reverse('welcome:products',kwargs={'pk':self.pk})"""

	def __str__(self):
		return self.title + '-'+ self.gender

		

		





		
		

welcome/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate, get_user_model, login, logout
from .models import CartP, Address, Order
from datetime import datetime 

User = get_user_model()

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','email','password']

class OrderForm(forms.ModelForm):
	date_placed = forms.DateTimeField(initial=datetime.now(), required=False)
	class Meta:
		model = Order
		fields = ['shipping_address']
		

class UserLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)


	
	def clean(self, *args, **kwargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get('password')
		if username and password:
			user = authenticate(username=username, password=password)
			if not user:
				raise forms.ValidationError("This User Does not exist")

			if not user.check_password(password):
				raise forms.ValidationError("Incorrect Password")
			if not user.is_active:
				raise forms.ValidationError("This User is no longer active")




class CartForm(forms.ModelForm):

    class Meta:
        model = CartP
        fields = ['product', 'size','delivery_date']

class AddressForm(forms.ModelForm):

	class Meta:
		model = Address
		fields = ['first_name','last_name','address_line','city','state','pincode','phone_number']

welcome/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.template import loader
from django.views import generic
from django.views.generic import DetailView
from django.views.generic.edit import FormMixin
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm, UserLoginForm, CartForm, AddressForm, OrderForm
from django.views.generic import View
from .models import Category, Product, Image, CartP, Address
from django.db.models import Sum
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from datetime import datetime

# Create your views here.
form = CartForm()
form2 = AddressForm()
form3 = OrderForm()
form4 = UserForm()
def index(request):
	template = loader.get_template('welcome/index.html')
	product = Product.objects.all()[0:5]
	return render(request,'welcome/index.html',{'product' : product})

def shop_man(request):
	template = loader.get_template('welcome/shop.html')
	category = Category.objects.filter(gender='Men')
	return render(request,'welcome/shop.html',{'category' : category})

def shop_women(request):
	template = loader.get_template('welcome/shop.html')
	category = Category.objects.filter(gender='Women')
	return render(request,'welcome/shop.html',{'category' : category})

def shop_kids(request):
	template = loader.get_template('welcome/shop.html')
	category = Category.objects.filter(gender='Kids')
	return render(request,'welcome/shop.html',{'category' : category})

def products(request, gender, id):
	template = loader.get_template('welcome/shop.html')
	product = Product.objects.filter(category=id)
	return render(request,'welcome/products.html',{'products' : product})


class DetailView(DetailView):
	model = Product
	template_name = 'welcome/detail.html'



def cart(request):
	if request.method == "POST":
		forma = CartForm(request.POST)
		if forma.is_valid():
			post = forma.save(commit=False)
			post.user = request.user
			post.save()
			print("hello")
		else:
			print("not valid")		
	else:
		print("Hi")
	products = CartP.objects.filter(user__username=request.user)
	sumi = CartP.objects.filter(user__username=request.user).aggregate(Sum('product__price'))
	return render(request,'welcome/cart.html',{'sumi':sumi,'products':products,'form':form3})

class ProductDelete(DeleteView):
	model = CartP
	success_url = reverse_lazy('welcome:cart')

"""def checkoutStep1(request):
	template = loader.get_template('welcome/step1.html')
	addre = Address.objects.filter(user__username=request.user)
	return render(request,'welcome/step1.html',{'addre':addre,'form' : form2})"""

class AddressFormView(View):
	form_class = AddressForm
	template_name = 'welcome/step1.html'	

	def get(self,request):
		form = self.form_class(None)
		addre = Address.objects.filter(user__username=request.user)
		return render(request,self.template_name,{'form':form,'addre':addre})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			post = form.save(commit=False)
			post.user = request.user
			post.save()

		return redirect('/checkout/step2/%s/' % post.pk)

def checkoutStep2(request):
	template = loader.get_template('welcome/step2.html')
	return render(request,'welcome/step2.html')


def checkoutStep3(request,id):
	addr = Address.objects.get(pk=id)
	products = CartP.objects.filter(user__username=request.user)
	sumi = CartP.objects.filter(user__username=request.user).aggregate(Sum('product__price'))
	return render(request,'welcome/step3.html',{'products' : products,'a':addr,'sumi':sumi})

def checkoutStep4(request):
	if request.method == "POST":
		forma = OrderForm(request.POST)
		if forma.is_valid():
			post = forma.save(commit=False)
			post.user = request.user
			post.date_placed = datetime.now
			post.save()
			CartP.objects.filter(user__username=request.user).delete()
			print("hello")
			return render(request,'welcome/step4.html',{'number':post})
		else:
			print("not valid")		
	else:
		print("Hi")
	template = loader.get_template('welcome/step4.html')
	return render(request,'welcome/step4.html')


class UserFormView(View):
	form_class = UserForm
	template_name = 'welcome/login.html'	

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form,'form2':form4})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)

			#cleaned (normalized) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			#returns user objects if credential are correct
			user = authenticate(username=username,password=password)

			if user is not None:

				if user .is_active:
					login(request, user)
					return redirect('welcome:index')

		return render(request,self.template_name,{'form':form})


class UserLoginView(View):
	form_class = UserLoginForm
	template_name = 'welcome/login.html'	

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():
			
			#cleaned (normalized) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			#returns user objects if credential are correct
			user = authenticate(username=username,password=password)

			if user is not None:

				if user .is_active:
					login(request, user)
					print(request.user.is_authenticated())
					return redirect('welcome:index')


		return render(request,self.template_name,{'form':form})


def logout_view(request):
    logout(request)
    return redirect('welcome:index')

welcome/templates/welcome/checkout_nav.html
{% load staticfiles %}
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'welcome/header_style.css' %}">
  <link rel="stylesheet" href="{% static 'welcome/style.css' %}">
  <style type="text/css">
  	body, .panel{
  		background-color: #f6f6f6;
  		letter-spacing: 3px;
  	}
  	.panel{
  		border: 1px solid black;
  	}
  	.panel-heading{
  		color: white;
  		background-color: #2d2d30;
      opacity: 0.9;
  	}
  	.navbar{
  		border-radius: 0px;

  	}

  	.l{
  		margin-left: 30px;
  	}
    .l:active a{
      background-color: black;
    }
    .btn {
    background-color: Transparent;
    background-repeat:no-repeat;
    border: 1px solid black;
    border-radius: 0px;
    padding: 8px;
    cursor:pointer;
    overflow: hidden;
    outline:none;
    letter-spacing: 2px;
}
.btn:hover {
        background-color: black;
        color: white;
    }
        a{
      color: black;
    }

  </style>

</head>
<br>
<h1 class="container">Dress Me Up</h1>
<br>
<nav class="navbar navbar-inverse">
  <div class="container">
    <ul class="nav navbar-nav">
      <li class="l"><a href="#" class="active">1.Shipping Address</a></li>
      <li class="l"><a href="#">2.Preview</a></li>
      <li class="l"><a href="#">3.Confirmation</a></li>

    </ul>
  </div>
</nav>
{% block body%}
{% endblock %}

welcome/templates/welcome/header.html
<!doctype html>
<html>
<head>
{% load staticfiles %}
<meta charset="utf-8">
  <title>{% block title %}Welcome{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'welcome/header_style.css' %}">
  <link rel="stylesheet" href="{% static 'welcome/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet">
</head>
<style type="stylesheet/css">
  .mega-dropdown-menu {
  display: block;
  color: #222;
  padding: 3px 5px;
}
</style>
<body>
<!--navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'welcome:index' %}">DressMeUp</a>
  </div>
  
  <div class="collapse navbar-collapse js-navbar-collapse">
    <ul class="nav navbar-nav">
      <li class="">
        <a href="{% url 'welcome:shop_man'%}">Men</a>        
        <ul class="dropdown-menu mega-dropdown-menu">
          <li class="col-sm-3">
            <ul>
              <li class="dropdown-header">Men Collection</li>                            
                            <div id="menCollection" class="carousel slide" data-ride="carousel">
                              <div class="carousel-inner">
                                <div class="item active">
                                    <a href="#"><img src="http://placehold.it/254x150/ff3546/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
                                    <h4><small>Summer dress floral prints</small></h4>                                        
                                    <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>       
                                </div><!-- End Item -->
                                <div class="item">
                                    <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
                                    <h4><small>Gold sandals with shiny touch</small></h4>                                        
                                    <button class="btn btn-primary" type="button">9,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>        
                                </div><!-- End Item -->
                                <div class="item">
                                    <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
                                    <h4><small>Denin jacket stamped</small></h4>                                        
                                    <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>      
                                </div><!-- End Item -->                                
                              </div><!-- End Carousel Inner -->
                              <!-- Controls -->
                              <!--<a class="left carousel-control" href="#menCollection" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                              </a>
                              <a class="right carousel-control" href="#menCollection" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                              </a>-->
                            </div><!-- /.carousel -->
                            <li class="divider"></li>
                            <li><a href="#">View all Collection <span class="glyphicon glyphicon-chevron-right pull-right"></span></a></li>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li class="dropdown-header">Features</li>
              <li><a href="#">Auto Carousel</a></li>
                            <li><a href="#">Carousel Control</a></li>
                            <li><a href="#">Left & Right Navigation</a></li>
              <li><a href="#">Four Columns Grid</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Fonts</li>
                            <li><a href="#">Glyphicon</a></li>
              <li><a href="#">Google Fonts</a></li>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li class="dropdown-header">Plus</li>
              <li><a href="#">Navbar Inverse</a></li>
              <li><a href="#">Pull Right Elements</a></li>
              <li><a href="#">Coloured Headers</a></li>                            
              <li><a href="#">Primary Buttons & Default</a></li>              
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li class="dropdown-header">Much more</li>
                            <li><a href="#">Easy to Customize</a></li>
              <li><a href="#">Calls to action</a></li>
              <li><a href="#">Custom Fonts</a></li>
              <li><a href="#">Slide down on Hover</a></li>                         
            </ul>
          </li>
        </ul>       
      </li>
            <li class="">
          <a href="{% url 'welcome:shop_women'%}">Women</span></a>        
        <ul class="dropdown-menu mega-dropdown-menu">
          <li class="col-sm-3">
              <ul>
              <li class="dropdown-header">Features</li>
              <li><a href="#">Auto Carousel</a></li>
                            <li><a href="#">Carousel Control</a></li>
                            <li><a href="#">Left & Right Navigation</a></li>
              <li><a href="#">Four Columns Grid</a></li>
              <li class="divider"></li>
              <li class="dropdown-header">Fonts</li>
                            <li><a href="#">Glyphicon</a></li>
              <li><a href="#">Google Fonts</a></li>
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li class="dropdown-header">Plus</li>
              <li><a href="#">Navbar Inverse</a></li>
              <li><a href="#">Pull Right Elements</a></li>
              <li><a href="#">Coloured Headers</a></li>                            
              <li><a href="#">Primary Buttons & Default</a></li>              
            </ul>
          </li>
          <li class="col-sm-3">
            <ul>
              <li class="dropdown-header">Much more</li>
                            <li><a href="#">Easy to Customize</a></li>
              <li><a href="#">Calls to action</a></li>
              <li><a href="#">Custom Fonts</a></li>
              <li><a href="#">Slide down on Hover</a></li>                         
            </ul>
          </li>
                    <li class="col-sm-3">
              <ul>
              <li class="dropdown-header">Women Collection</li>                            
                            <div id="womenCollection" class="carousel slide" data-ride="carousel">
                              <div class="carousel-inner">
                                <div class="item active">
                                    <a href="#"><img src="http://placehold.it/254x150/3498db/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 1"></a>
                                    <h4><small>Summer dress floral prints</small></h4>                                        
                                    <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>       
                                </div><!-- End Item -->
                                <div class="item">
                                    <a href="#"><img src="http://placehold.it/254x150/ff3546/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 2"></a>
                                    <h4><small>Gold sandals with shiny touch</small></h4>                                        
                                    <button class="btn btn-primary" type="button">9,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>        
                                </div><!-- End Item -->
                                <div class="item">
                                    <a href="#"><img src="http://placehold.it/254x150/2ecc71/f5f5f5/&text=New+Collection" class="img-responsive" alt="product 3"></a>
                                    <h4><small>Denin jacket stamped</small></h4>                                        
                                    <button class="btn btn-primary" type="button">49,99 €</button> <button href="#" class="btn btn-default" type="button"><span class="glyphicon glyphicon-heart"></span> Add to Wishlist</button>      
                                </div><!-- End Item -->                                
                              </div><!-- End Carousel Inner -->
                              <!-- Controls -->
                              <!--<a class="left carousel-control" href="#womenCollection" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                              </a>
                              <a class="right carousel-control" href="#womenCollection" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                              </a>-->
                            </div>
                            <!-- /.carousel -->
                            <li class="divider"></li>
                            <li><a href="#">View all Collection <span class="glyphicon glyphicon-chevron-right pull-right"></span></a></li>
            </ul>
          </li>
        </ul>       
      </li>
            <li><a href="{% url 'welcome:shop_kids'%}">Kids</a></li>
    </ul>
    
        <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user" aria-hidden="true"></i> {{ user.username}} <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li style="background-color: white;color:black; "><a href="{% url 'welcome:logout' %}">logout</a></li>
          </ul>
        </li>
        <li><a href="{% url 'welcome:cart' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i> My cart </a></li>
        {% else %}
        <li><a href="{% url 'welcome:login' %}"><span class="glyphicon glyphicon-user"></span>&nbsp; SignIn/Up </a></li>
        {% endif %}

      </ul>
  </div><!-- /.nav-collapse -->
  </nav>
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideDown("400");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideUp("400");
            $(this).toggleClass('open');       
        }
    );
    $('#myCarousel').carousel({
    interval: 1000 * 1;
});
});
</script>

  {% block body %}
  {% endblock %}
  </body>
</html>

welcome/templates/welcome/step1.html
{% extends 'welcome/checkout_nav.html' %}
{% load staticfiles %}
{% block body %}
<br>


<div class="container">
<div class="col-sm-12">
<div class="choose-block">
    <div class="row">
<div class="col-sm-6">
<!--SHIPPING METHOD-->
<div class="panel">
    <div class="panel-heading">Address</div>
    <div class="panel-body">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-md-12">
                <h4>Shipping Address</h4>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-xs-12">
                <strong>First Name:</strong>
                <input type="text" name="first_name" class="form-control" id="id_first_name" required="true" />
            </div>
            <div class="span1"></div>
            <div class="col-md-6 col-xs-12">
                <strong>Last Name:</strong>
                <input type="text" name="last_name" class="form-control" id="id_last_name" required="true" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12"><strong>Address:</strong></div>
            <div class="col-md-12">
                <input type="text" name="address_line" class="form-control" id="id_address_line" required="true" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12"><strong>City:</strong></div>
            <div class="col-md-12">
                <input type="text" name="city" class="form-control" id="id_city" required="true" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12"><strong>State:</strong></div>
            <div class="col-md-12">
                <input type="text" name="state" class="form-control" id="id_state" required="true" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12"><strong>Zip / Postal Code:</strong></div>
            <div class="col-md-12">
                <input type="text" name="pincode" class="form-control" id="id_pincode" required="true" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12"><strong>Phone Number:</strong></div>
            <div class="col-md-12"><input type="text" name="phone_number" class="form-control" id="id_phone_number" required="true" /></div>
        </div>
        <div class="form-group">
        <div class="col-md-12"><br></div>
        
            <div class="col-md-4"><input type="submit" name="continue" class="form-control btn" value="Continue"/></div>
             <div class="col-md-4 pull-right"><a href="{% url 'welcome:cart' %}"><input type="button" class="form-control btn" value="Return to Cart"/></a></div>
        </div>
        </form>
      </div>
    </div>
</div>

<div class="col-sm-6">
    <h5> An address from your address book?</h5>
    {% for a in addre %}
        <div class="well">

            <address>

                <span>{{ a.first_name}} {{a.last_name}}</span><br>
                <span>{{a.address_line}}</span><br>
                <span>{{a.city}}</span><br>
                <span>{{a.state}}</span><br>
                <span>{{a.pincode}}</span><br>
                <span>{{a.phone_number}}</span><br>
                <span>India</span>


            </address>
            <!--<form action="" method="post" id="select_shipping_address_{{ address.id }}">
    }
-->
            <a href="{% url 'welcome:step3' a.id %}"><button type="submit" class="btn">Ship to this address</button></a>
        </div>
    {% endfor %}
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

welcome/templates/welcome/step4.html
{% extends 'welcome/checkout_nav.html' %}
{% load staticfiles %}
{% block body %}
 <style type="text/css">
        .btn {
    background-color: Transparent;
    background-repeat:no-repeat;
    border: 1px solid black;
    padding: 8px;
    cursor:pointer;
    overflow: hidden;
    outline:none;
}
.btn:hover {
        background-color: black;
        color: white;
    }
        a{
        color: black;
    }

    </style>
    <center>
<div class="container" style="letter-spacing: 4px;font-size: 30px;margin-top: 40px;">Thank You !! Your Order has been placed !! Your Order Number is {{number.id}}</div>
<a href="{% url 'welcome:index' %}" >
                        <button type="button" class="btn">
                            Continue Shopping
                        </button></a></td>
                        </center>
{% endblock %}